drivers:OA staging: prima: fix undeclared identifier 'eLIM_AUTH_SAE_TIMER'
Since tag 'LA.UM.8.6.r1-02600-89xx.0' prima wlan has updated and implemented AUTH_SAE_TIMER on the hood,
somehow that code isn't read by kernel during guard by config 'WLAN_FEATURE_LFR_MBB' that prima or kernel defconfig isn't used it by itself (even after regenerate).

So 'eLIM_AUTH_SAE_TIMER' function can't be read and throw error

../drivers/staging/prima/CORE/MAC/src/pe/lim/limTimerUtils.c:1956:10: error: use of undeclared identifier 'eLIM_AUTH_SAE_TIMER'
    case eLIM_AUTH_SAE_TIMER:
         ^
1 error generated

During compile, currently workaround for now is move that function before that guarded definition to make kernel read
that definition and pass the compiling progress. It's already test and wifi work correctly with no problem.

Signed-off-by: Dicky Herlambang <herlambangdicky5@gmail.com>